steps:
  build:
    image: ubuntu:noble
    commands:
      - apt-get update
      - >-
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
        cmake git ca-certificates ninja-build
        clang-17 clang-tools-17 lld-17
        libc++-17-dev-wasm32 libclang-rt-17-dev-wasm32
      - mkdir build
      - >-
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_C_COMPILER=clang-17 -DCMAKE_CXX_COMPILER=clang++-17
        -S . -B build 2>&1 | tee build/cmake-configure.log
      - cmake --build build --parallel=2 2>&1 | tee build/cmake-build.log
